/**
 * Client-side SFU adapter interface.
 *
 * Sockr defines this contract; engineers implement it (or use the
 * shipped LiveKitClientAdapter). The adapter owns the SFU SDK lifecycle
 * so Sockr never needs to know which SFU is in use.
 */
export interface ISFUClientAdapter {
  /**
   * Connect to the SFU room using the token delivered by the server.
   *
   * @param sfuUrl  WebSocket URL of the SFU server (e.g. wss://livekit.example.com).
   * @param token   Short-lived JWT generated by the server.
   * @param opts    Optional connection hints (audio/video tracks to publish, etc.).
   */
  connect(sfuUrl: string, token: string, opts?: SFUConnectOptions): Promise<void>;

  /** Gracefully disconnect from the room. */
  disconnect(): Promise<void>;

  /**
   * Publish local media tracks to the room.
   * Called after connect() if tracks were not published during connect.
   */
  publishTracks(opts?: SFUPublishOptions): Promise<void>;

  /**
   * Called when a remote participant publishes a new track.
   * The adapter should attach the track to the provided container element
   * (or expose it via the callback if no element is supplied).
   */
  onTrackSubscribed(
    handler: (track: MediaStreamTrack, participantId: string) => void
  ): void;

  /** Called when a remote participant unpublishes or disconnects. */
  onTrackUnsubscribed(
    handler: (track: MediaStreamTrack, participantId: string) => void
  ): void;

  /** Called when a participant joins the room (includes self after connect). */
  onParticipantConnected(handler: (participantId: string) => void): void;

  /** Called when a participant leaves the room. */
  onParticipantDisconnected(handler: (participantId: string) => void): void;

  /** Called when the local connection to the SFU is lost. */
  onDisconnected(handler: () => void): void;
}

export interface SFUConnectOptions {
  /** Publish audio immediately on connect. Default: true. */
  audio?: boolean;
  /** Publish video immediately on connect. Default: false. */
  video?: boolean;
}

export interface SFUPublishOptions {
  audio?: boolean;
  video?: boolean;
}
